version: "3.9"

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    environment:
      - URL=jdbc:postgresql://postgres:5432/postgres
      - USERNAME=postgres
      - PASSWORD=123
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    #image: nginx:latest
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/public/:/usr/share/nginx/public/
    depends_on:
      - app

  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
